# Generated by Django 4.2.11 on 2024-04-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dishlist.category'),
        ),
    ]
