# Generated by Django 4.2.11 on 2024-04-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0002_alter_dishes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_place', models.CharField(db_index=True, max_length=150, verbose_name='Заведение')),
            ],
        ),
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishlist.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dishlist.place', verbose_name='Заведение'),
            preserve_default=False,
        ),
    ]
