# Generated by Django 4.2.11 on 2024-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0008_delete_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisheLable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishe_lable',
            field=models.ManyToManyField(blank=True, to='dishlist.dishelable'),
        ),
    ]
