# Generated by Django 4.2.11 on 2024-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0009_dishelable_dishes_dishe_lable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Текст плашки')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('label', models.ManyToManyField(to='dishlist.labeltext', verbose_name='Тексты плашек')),
            ],
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='dishe_lable',
        ),
        migrations.DeleteModel(
            name='DisheLable',
        ),
        migrations.AddField(
            model_name='place',
            name='labels',
            field=models.ManyToManyField(blank=True, to='dishlist.placelabel'),
        ),
    ]
