# Generated by Django 4.2.11 on 2024-05-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0010_labeltext_placelabel_remove_dishes_dishe_lable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='placelabel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='placelabel',
            name='label',
        ),
        migrations.AddField(
            model_name='place',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishlist.placelabel', verbose_name='Плашка'),
        ),
        migrations.AddField(
            model_name='placelabel',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Текст плашки'),
        ),
        migrations.DeleteModel(
            name='LabelText',
        ),
    ]
