# Generated by Django 4.2.11 on 2024-05-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0011_remove_place_labels_remove_placelabel_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='label',
        ),
        migrations.DeleteModel(
            name='PlaceLabel',
        ),
    ]
