# Generated by Django 4.2.11 on 2024-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basketitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
