# Generated by Django 4.2.11 on 2024-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_basketitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='basket.basketitem')),
            ],
        ),
    ]
